In [25]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output

import tensorflow.compat.v2.feature_column as fc

In [26]:
string = tf.Variable("this is a string", tf.string)
number= tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [27]:
rank1_tensor = tf.Variable(["test", "ok", "vipul"], tf.string)
rank2_tensor= tf.Variable([['test', 'ok'], ["test1", "yes"]], tf.string)

In [28]:
tf.rank(rank1_tensor), tf.rank(rank2_tensor), tf.rank(number)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>)

In [29]:
rank1_tensor.shape, rank2_tensor.shape, number.shape

(TensorShape([3]), TensorShape([2, 2]), TensorShape([]))

In [30]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, shape=[2,3,1])
tensor3 = tf.reshape(tensor2, shape= [3, -1])
print(tensor1)
print("--------------------")
print(tensor2)
print("--------------------")
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
--------------------
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
--------------------
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [31]:
# t = tf.zeros([5,5,5,5])
# t

In [32]:
# t= tf.reshape(t, shape= [625])
# t

In [33]:
# t= tf.reshape(t, shape= [125, -1])
# t

####
Tensorflow core learning algorithms

In [34]:
## Linear Regression
